const mongoose =require("mongoose");

const recipeSchema =new mongoose.Schema({
    name_en:{
        type:String,
        required:true,
    },
    name_ar:{
        type:String,
        required:true,
    },
    calories_en:{
        type:String,
        required:true,
    },
    calories_ar:{
        type:String,
        required:true,
    },
    country_en:{
        type:String,
        required:true,
    },
    country_ar:{
        type:String,
        required:true,
    },
    total_time_en:{
        type:String,
        required:true,
    },
    total_time_ar:{
        type:String,
        required:true,
    },
    serving_en:{
        type:String,
        required:true,
    },
    serving_ar:{
        type:String,
        required:true,
    },
    difficulty_en:{
        type:String,
        required:true,
    },
    difficulty_ar:{
        type:String,
        required:true,
    },
    categorie_en:{
        type:String,
    },
    categorie_ar:{
        type:String,
    },
    image:{
        type:String,
        default:"",
    },
    ingredients_en:[{
        type:String,
        required:true,
    }],
    instructions_en:[{
        type:String,
        required:true,
    }],
    ingredients_ar:[{
        type:String,
        required:true,
    }],
    instructions_ar:[{
        type:String,
        required:true,
    }],
}) 

const Recipe=mongoose.model("Recipe",recipeSchema);
module.exports=Recipe;