const mongoose =require("mongoose");

const recipeSchema =new mongoose.Schema({
    name:{
        type:String,
        required:true,
    },
    name_ar:{
        type:String,
        required:true,
    },
    calories:{
        type:String,
        required:true,
    },
    calories_ar:{
        type:String,
        required:true,
    },
    country:{
        type:String,
        required:true,
    },
    country_ar:{
        type:String,
        required:true,
    },
    total_time:{
        type:String,
        required:true,
    },
    total_time_ar:{
        type:String,
        required:true,
    },
    serving:{
        type:String,
        required:true,
    },
    serving_ar:{
        type:String,
        required:true,
    },
    difficulty:{
        type:String,
        required:true,
    },
    difficulty_ar:{
        type:String,
        required:true,
    },
    categorie:{
        type:String,
    },
    categorie_ar:{
        type:String,
    },
    image:{
        type:String,
        default:"",
    },
    ingredients:[{
        type:String,
        required:true,
    }],
    instructions:[{
        type:String,
        required:true,
    }],
    ingredients_ar:[{
        type:String,
        required:true,
    }],
    instructions_ar:[{
        type:String,
        required:true,
    }],
}) 

const Recipe=mongoose.model("Recipe",recipeSchema);
module.exports=Recipe;